### ISSUE TITLE
Negative Sampling

### ISSUE THREAD

**Issue by sciprogramming** [orenmel/context2vec#13]
Hi
In the context of negative sampling the paper mentions 10 samples. This would suggest 10 independently sampled tokens for every word-context. In the code where the loss function calculation is [called](https://github.com/orenmel/context2vec/blob/master/context2vec/common/context_models.py#L221) it seems the same sample of 10 tokens would be used for all the B=100 'first word' contexts, then a different sample of 10 tokens would be used for the next B=100 'second word' contexts and so on. Is my understanding correct?

**Comment by orenmel** [comment]
Hi. No. The Chainer's negative sampling loss function that I'm using, samples n different tokens for every item in its input mini-batch. So for B=100, and n=10, you'll get 1,000 sampled tokens altogether for each step, or 10 different sampled tokens for every individual context.

**Comment by rbarve** [comment]
Ok thanks, Oren ; thanks for that helpful clarification.
