### ISSUE TITLE
Can't download pre-trained models

### ISSUE THREAD

**Issue by kyoungrok0517** [orenmel/context2vec#17]
Hi, the [link](
http://u.cs.biu.ac.il/%7Enlp/resources/downloads/context2vec/) for the pre-trained models is dead. Can you please check?

**Comment by orenmel** [comment]
It seems like the entire website of the nlp lab is down. I have sent them a
message regarding this. Please try again in a couple of days.

**Comment by kyoungrok0517** [comment]
Thanks!

**Comment by tim-hari** [comment]
Hi, Facing the same issue.

Cannot download the pre-trained context2vec-model from following link
http://u.cs.biu.ac.il/%7Enlp/resources/downloads/context2vec/ 

Could you please help.

**Comment by orenmel** [comment]
The problem was fixed. Please try again now.

**Comment by tim-hari** [comment]
> The problem was fixed. Please try again now.

Thank you, its working.
