### ISSUE TITLE
Tokenizer for using UKWac model

### ISSUE THREAD

**Issue by maehster** [orenmel/context2vec#7]
Dear creator (@orenmel),

I am currently using your great tool and the pre-trained UKWaC model to create context vectors for target words in Wikipedia sentences. 

To my questions: 1. Do you use the default UKWaC tokenization as input for the training? 2. Which tokenizer should I use for new input at test time in order to make the best out of the model? (Do you have any suggestions?)

Best regards,
David

**Comment by orenmel** [comment]
Hi David,

1. Yes. I believe we used the default UkWaC tokenization.
2. At test time, we used NLTK tokenizers (see for example mscc_text_tokenize.py) and that worked fine. Do make sure to also lowercase the input.

Oren.

PS: For your use case, it seems like a model trained on Wikipedia would be best. If you happen to have the time and resources to train a context2vec Wikipedia model, I'd be happy to know about it.

**Comment by maehster** [comment]
Thanks for the information, Oren!

Im aware that it might be not optimal to use the UKWaC model on Wikipedia data but at the moment I only have (non-admin) access to GPUs that run on Cuda 8.0 which causes problems with Chainer 1.7. Due to time limitations, CPU training will be too slow, so I have to stick with UKWaC.
